"""init books with uuid string and imagem_url

Revision ID: d3062058b537
Revises: 
Create Date: 2025-09-28 15:41:51.290354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3062058b537'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('autores', sa.String(length=300), nullable=False),
    sa.Column('paginas', sa.Integer(), nullable=False),
    sa.Column('ano_publicacao', sa.Integer(), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
